name: Pylint and Autoformat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Autoformat code with black
      run: |
        black $(git ls-files '*.py')
    - name: Commit and push changes
      if: github.ref == 'refs/heads/Django_Rest_Api/patch-1' 
      run: |
        git config --global user.email "ci@example.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Autoformatted code with black" || echo "No changes to commit"
        git push
